#Configuration File#

#Set resolution
resolution:
  x:  500
  y:  300

#log directory
#log_path:     "C:/Users/user/Desktop/Valence_Logs"
#TODO: implement configurable logging directory


#String Configuration
num_strings:  19
strings:
  1:
    - 1
    - 2
    - 3
    - 4
  2:
  - 5
  - 6
  - 7
  - 8
  3:
  - 9
  - 10
  - 11
  - 12
  4:
  - 13
  - 14
  - 15
  - 16
  5:
  - 17
  - 18
  - 19
  - 20
  6:
  - 21
  - 22
  - 23
  - 24
  7:
  - 25
  - 26
  - 27
  - 28
  8:
  - 29
  - 30
  - 31
  - 32
  9:
  - 33
  - 34
  - 35
  - 36
  10:
  - 37
  - 38
  - 39
  - 40
  11:
  - 41
  - 42
  - 43
  - 44
  12:
  - 45
  - 46
  - 47
  - 48
  13:
  - 49
  - 50
  - 51
  - 52
  14:
  - 53
  - 54
  - 55
  - 56
  15:
  - 57
  - 58
  - 59
  - 60
  16:
  - 61
  - 62
  - 63
  - 64
  17:
  - 65
  - 66
  - 67
  - 68
  18:
  - 69
  - 70
  - 71
  - 72
  19:
  - 73
  - 74
  - 75
  - 76
