#Configuration File#

#Set resolution
resolution:
  x:  1200
  y:  1000

#defaults
COM: 'COM4'
ID: 1
log_path: "C:\\Users\\user\\Desktop\\Valence\\Valence_Logs"


#how many columns this program will use to display all strings
num_string_columns: 5

#String Configuration
num_strings:  19
strings:
  1:
    - 1
    - 2
    - 3
    - 4
  2:
  - 5
  - 6
  - 7
  - 8
  3:
  - 9
  - 10
  - 11
  - 12
  4:
  - 13
  - 14
  - 15
  - 16
  5:
  - 17
  - 18
  - 19
  - 20
  6:
  - 21
  - 22
  - 23
  - 24
  7:
  - 25
  - 26
  - 27
  - 28
  8:
  - 29
  - 30
  - 31
  - 32
  9:
  - 33
  - 34
  - 35
  - 36
  10:
  - 37
  - 38
  - 39
  - 40
  11:
  - 41
  - 42
  - 43
  - 44
  12:
  - 45
  - 46
  - 47
  - 48
  13:
  - 49
  - 50
  - 51
  - 52
  14:
  - 53
  - 54
  - 55
  - 56
  15:
  - 57
  - 58
  - 59
  - 60
  16:
  - 61
  - 62
  - 63
  - 64
  17:
  - 65
  - 66
  - 67
  - 68
  18:
  - 69
  - 70
  - 71
  - 72
  19:
  - 73
  - 74
  - 75
  - 76


#path to Valence Software if different from default (rare)
path_to_valence: 'C:\Program Files (x86)\Valence Technology Inc\Valence U-Charge XP Module Diagnostics Software\ModuleDiagG2.exe'
